JalgrattaeksamMVC/Controllers/EksamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JalgrattaeksamMVC.Data;
using JalgrattaeksamMVC.Models;

namespace JalgrattaeksamMVC.Controllers
{
    public class EksamsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EksamsController(ApplicationDbContext context)
        {
            _context = context;
        }


        // POST: Eksams/TeooriaTulemus
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.




        public async Task<IActionResult> PassFail(int id,string Osa,int tulemus)
        {
            var eksam = await _context.Eksam.FindAsync(id);
            if (eksam == null)
            {
                return NotFound();
            }

            switch(Osa)
            {
                case nameof(eksam.Slaalom):
                    {
                        eksam.Slaalom = tulemus;
                        break;

                    }
                case nameof(eksam.Ring):
                    {
                        eksam.Slaalom = tulemus;
                        break;

                    }
                case nameof(eksam.Tänav):
                    {
                        eksam.Slaalom = tulemus;
                        break;

                    }
                default:
                    {
                        return NotFound();
                    }

                   
            }
            try
            {
                _context.Update(eksam);
                await _context.SaveChangesAsync();
            }
            catch(DbUpdateConcurrencyException)
            {
                if(!EksamExists(eksam.Id))
                {
                    return NotFound();
                }
            }


            return RedirectToAction(Osa);
        }

        
        public async Task<IActionResult> Slaalom()
        {
            var model = _context.Eksam.Where(e => e.Teooria >= 9 && e.Slaalom == -1);
            return View(await model.ToListAsync());
        }

        public async Task<IActionResult> Ring()
        {
            var model = _context.Eksam.Where(e => e.Teooria >= 9 && e.Ring == -1);
            return View(await model.ToListAsync());
        }


        public async Task<IActionResult> Tänav()
        {
            var model = _context.Eksam.Where(e => e.Ring == 1 && e.Slaalom == 1 && e.Tänav ==-1);
            return View(await model.ToListAsync());
        }


        public async Task<IActionResult> Luba()
        {
            var model = _context.Eksam.Select(e =>
            new LubaViewModel()
            {
                Id = e.Id,
                Eesnimi = e.Eesnimi,
                Perenimi = e.Perenimi,
                Teooria = e.Teooria,
                Ring = e.Ring ==-1?".":e.Ring==1?"õnnestunud":"Põrus",
                Slaalom = e.Slaalom == -1 ? "." : e.Slaalom == 1 ? "õnnestunud" : "Põrus",
                Tänav = e.Tänav == -1 ? "." : e.Tänav == 1 ? "õnnestunud" : "Põrus",
                Luba = e.Luba == 1?"väljastatud": e.Tänav == 1 ? "Väljasta" : "."


            });
            return View(await model.ToListAsync());
        }
        
        public async Task<IActionResult> VäljastaLuba(int id)
        {
            var model = await _context.Eksam.FindAsync(id);
            if (model == null)
            {
                return NotFound();
            }
            if (model.Tänav == 1)
            {
                model.Luba = 1;
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EksamExists(model.Id))
                    {
                        return NotFound();
                    }
                }
            }



            return RedirectToAction(nameof(Luba));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> TeooriaTulemus( [Bind("Id,Teooria")] Eksam tulemus)
        {
            var eksam = await _context.Eksam.FindAsync(tulemus.Id);
            if (eksam == null)
            {
                return NotFound();
            }
            eksam.Teooria = tulemus.Teooria;

           
                try
                {
                    _context.Update(eksam);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EksamExists(eksam.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
             
            
              return RedirectToAction(nameof(Teooria));
        }



        // GET: Eksams
        public async Task<IActionResult> Teooria()
        {
            var model = _context.Eksam.Where(e => e.Teooria == -1);
            return View(await model.ToListAsync());
        }


        // GET: Eksams/Create
        public IActionResult Registreeri()
        {
            return View();
        }

        // POST: Eksams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Registreeri([Bind("Id,Eesnimi,Perenimi")] Eksam eksam)
        {
            if (ModelState.IsValid)
            {
                _context.Add(eksam);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(eksam);
        }




        // GET: Eksams
        public async Task<IActionResult> Index()
        {
            return View(await _context.Eksam.ToListAsync());
        }

        // GET: Eksams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eksam = await _context.Eksam
                .FirstOrDefaultAsync(m => m.Id == id);
            if (eksam == null)
            {
                return NotFound();
            }

            return View(eksam);
        }

        // GET: Eksams/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Eksams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Eesnimi,Perenimi,Teooria,Slaalom,Ring,Tänav,Luba")] Eksam eksam)
        {
            if (ModelState.IsValid)
            {
                _context.Add(eksam);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(eksam);
        }

        // GET: Eksams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eksam = await _context.Eksam.FindAsync(id);
            if (eksam == null)
            {
                return NotFound();
            }
            return View(eksam);
        }

        // POST: Eksams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Eesnimi,Perenimi,Teooria,Slaalom,Ring,Tänav,Luba")] Eksam eksam)
        {
            if (id != eksam.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(eksam);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EksamExists(eksam.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(eksam);
        }

        // GET: Eksams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eksam = await _context.Eksam
                .FirstOrDefaultAsync(m => m.Id == id);
            if (eksam == null)
            {
                return NotFound();
            }

            return View(eksam);
        }

        // POST: Eksams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var eksam = await _context.Eksam.FindAsync(id);
            _context.Eksam.Remove(eksam);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EksamExists(int id)
        {
            return _context.Eksam.Any(e => e.Id == id);
        }
    }
}

JalgrattaeksamMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JalgrattaeksamMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Eksams" asp-action="">JalgrattaeksamMVC</a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Eksams" asp-action="Tänav">Tänav</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Eksams" asp-action="Slaalom">Slaalom</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Eksams" asp-action="Ring">Ring</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Eksams" asp-action="Luba">Luba</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - JalgrattaeksamMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>